apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: {{ .Values.namespace }}           # ðŸ‘ˆ ensures it's isolated in {{ .Values.namespace }}
  labels:
    app: auth
    environment: {{ .Values.namespace }}        # ðŸ‘ˆ helps identify environment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth
      environment: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        app: auth
        environment: {{ .Values.namespace }}
    spec:
      nodeSelector:
        environment: {{ .Values.namespace }}  # ðŸ‘ˆ schedules this on {{ .Values.namespace }} node pool
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: DATABASE_URL
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: SECRET_KEY
          volumeMounts:
            - name: mysql-ssl-cert-volume
              mountPath: /app/ssl
              readOnly: true      
      volumes:
        - name: mysql-ssl-cert-volume
          secret:
            secretName: {{ .Release.Name }}-secret  # Name of the secret containing the certificate
            items:
              - key: DigiCertGlobalRootCA.crt.pem
                path: DigiCertGlobalRootCA.crt.pem          
        
            
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
  labels:
    app: auth
    environment: {{ .Values.namespace }}
spec:
  selector:
    app: auth
    environment: {{ .Values.namespace }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP